version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: quarterly

updates:
  - package-ecosystem: uv
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    cooldown:
      default-days: 14

  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    cooldown:
      default-days: 14
