[tox]
env_list = py313, py314, lint, type
isolated_build = true

[testenv]
extras = test
commands =
    coverage run -m pytest {posargs}
    coverage report

[testenv:lint]
skip_install = true
deps = ruff>=0.11
commands = ruff check .

[testenv:type]
extras = test
commands = mypy
